package eubrazil.atmosphere.util;

import java.util.Arrays;
import java.util.Collection;
import java.util.stream.Collectors;

public enum Country {
  AF("Afghanistan", "AF", "AFG", false),
  AX("Åland Islands", "AX", "ALA", false),
  AL("Albania", "AL", "ALB", false),
  DZ("Algeria", "DZ", "DZA", false),
  AS("American Samoa", "AS", "ASM", false),
  AD("Andorra", "AD", "AND", false),
  AO("Angola", "AO", "AGO", false),
  AI("Anguilla", "AI", "AIA", false),
  AQ("Antarctica", "AQ", "ATA", false),
  AG("Antigua and Barbuda", "AG", "ATG", false),
  AR("Argentina", "AR", "ARG", false),
  AM("Armenia", "AM", "ARM", false),
  AW("Aruba", "AW", "ABW", false),
  AU("Australia", "AU", "AUS", false),
  AT("Austria", "AT", "AUT", true),
  AZ("Azerbaijan", "AZ", "AZE", false),
  BS("Bahamas", "BS", "BHS", false),
  BH("Bahrain", "BH", "BHR", false),
  BD("Bangladesh", "BD", "BGD", false),
  BB("Barbados", "BB", "BRB", false),
  BY("Belarus", "BY", "BLR", false),
  BE("Belgium", "BE", "BEL", true),
  BZ("Belize", "BZ", "BLZ", false),
  BJ("Benin", "BJ", "BEN", false),
  BM("Bermuda", "BM", "BMU", false),
  BT("Bhutan", "BT", "BTN", false),
  BO("Bolivia (Plurinational State of)", "BO", "BOL", false),
  BQ("Bonaire, Sint Eustatius and Saba", "BQ", "BES", false),
  BA("Bosnia and Herzegovina", "BA", "BIH", false),
  BW("Botswana", "BW", "BWA", false),
  BV("Bouvet Island", "BV", "BVT", false),
  BR("Brazil", "BR", "BRA", false),
  IO("British Indian Ocean Territory", "IO", "IOT", false),
  BN("Brunei Darussalam", "BN", "BRN", false),
  BG("Bulgaria", "BG", "BGR", true),
  BF("Burkina Faso", "BF", "BFA", false),
  BI("Burundi", "BI", "BDI", false),
  CV("Cabo Verde", "CV", "CPV", false),
  KH("Cambodia", "KH", "KHM", false),
  CM("Cameroon", "CM", "CMR", false),
  CA("Canada", "CA", "CAN", false),
  KY("Cayman Islands", "KY", "CYM", false),
  CF("Central African Republic", "CF", "CAF", false),
  TD("Chad", "TD", "TCD", false),
  CL("Chile", "CL", "CHL", false),
  CN("China", "CN", "CHN", false),
  CX("Christmas Island", "CX", "CXR", false),
  CC("Cocos (Keeling) Islands", "CC", "CCK", false),
  CO("Colombia", "CO", "COL", false),
  KM("Comoros", "KM", "COM", false),
  CG("Congo", "CG", "COG", false),
  CD("Congo (Democratic Republic of the)", "CD", "COD", false),
  CK("Cook Islands", "CK", "COK", false),
  CR("Costa Rica", "CR", "CRI", false),
  CI("Côte d'Ivoire", "CI", "CIV", false),
  HR("Croatia", "HR", "HRV", true),
  CU("Cuba", "CU", "CUB", false),
  CW("Curaçao", "CW", "CUW", false),
  CY("Cyprus", "CY", "CYP", true),
  CZ("Czechia", "CZ", "CZE", true),
  DK("Denmark", "DK", "DNK", true),
  DJ("Djibouti", "DJ", "DJI", false),
  DM("Dominica", "DM", "DMA", false),
  DO("Dominican Republic", "DO", "DOM", false),
  EC("Ecuador", "EC", "ECU", false),
  EG("Egypt", "EG", "EGY", false),
  SV("El Salvador", "SV", "SLV", false),
  GQ("Equatorial Guinea", "GQ", "GNQ", false),
  ER("Eritrea", "ER", "ERI", false),
  EE("Estonia", "EE", "EST", true),
  ET("Ethiopia", "ET", "ETH", false),
  FK("Falkland Islands (Malvinas)", "FK", "FLK", false),
  FO("Faroe Islands", "FO", "FRO", false),
  FJ("Fiji", "FJ", "FJI", false),
  FI("Finland", "FI", "FIN", true),
  FR("France", "FR", "FRA", true),
  GF("French Guiana", "GF", "GUF", false),
  PF("French Polynesia", "PF", "PYF", false),
  TF("French Southern Territories", "TF", "ATF", false),
  GA("Gabon", "GA", "GAB", false),
  GM("Gambia", "GM", "GMB", false),
  GE("Georgia", "GE", "GEO", false),
  DE("Germany", "DE", "DEU", true),
  GH("Ghana", "GH", "GHA", false),
  GI("Gibraltar", "GI", "GIB", false),
  GR("Greece", "GR", "GRC", true),
  GL("Greenland", "GL", "GRL", false),
  GD("Grenada", "GD", "GRD", false),
  GP("Guadeloupe", "GP", "GLP", false),
  GU("Guam", "GU", "GUM", false),
  GT("Guatemala", "GT", "GTM", false),
  GG("Guernsey", "GG", "GGY", false),
  GN("Guinea", "GN", "GIN", false),
  GW("Guinea-Bissau", "GW", "GNB", false),
  GY("Guyana", "GY", "GUY", false),
  HT("Haiti", "HT", "HTI", false),
  HM("Heard Island and McDonald Islands", "HM", "HMD", false),
  VA("Holy See", "VA", "VAT", false),
  HN("Honduras", "HN", "HND", false),
  HK("Hong Kong", "HK", "HKG", false),
  HU("Hungary", "HU", "HUN", true),
  IS("Iceland", "IS", "ISL", false),
  IN("India", "IN", "IND", false),
  ID("Indonesia", "ID", "IDN", false),
  IR("Iran (Islamic Republic of)", "IR", "IRN", false),
  IQ("Iraq", "IQ", "IRQ", false),
  IE("Ireland", "IE", "IRL", true),
  IM("Isle of Man", "IM", "IMN", false),
  IL("Israel", "IL", "ISR", false),
  IT("Italy", "IT", "ITA", true),
  JM("Jamaica", "JM", "JAM", false),
  JP("Japan", "JP", "JPN", false),
  JE("Jersey", "JE", "JEY", false),
  JO("Jordan", "JO", "JOR", false),
  KZ("Kazakhstan", "KZ", "KAZ", false),
  KE("Kenya", "KE", "KEN", false),
  KI("Kiribati", "KI", "KIR", false),
  KP("Korea (Democratic People's Republic of)", "KP", "PRK", false),
  KR("Korea (Republic of)", "KR", "KOR", false),
  KW("Kuwait", "KW", "KWT", false),
  KG("Kyrgyzstan", "KG", "KGZ", false),
  LA("Lao People's Democratic Republic", "LA", "LAO", false),
  LV("Latvia", "LV", "LVA", true),
  LB("Lebanon", "LB", "LBN", false),
  LS("Lesotho", "LS", "LSO", false),
  LR("Liberia", "LR", "LBR", false),
  LY("Libya", "LY", "LBY", false),
  LI("Liechtenstein", "LI", "LIE", false),
  LT("Lithuania", "LT", "LTU", true),
  LU("Luxembourg", "LU", "LUX", true),
  MO("Macao", "MO", "MAC", false),
  MK("Macedonia (the former Yugoslav Republic of)", "MK", "MKD", false),
  MG("Madagascar", "MG", "MDG", false),
  MW("Malawi", "MW", "MWI", false),
  MY("Malaysia", "MY", "MYS", false),
  MV("Maldives", "MV", "MDV", false),
  ML("Mali", "ML", "MLI", false),
  MT("Malta", "MT", "MLT", true),
  MH("Marshall Islands", "MH", "MHL", false),
  MQ("Martinique", "MQ", "MTQ", false),
  MR("Mauritania", "MR", "MRT", false),
  MU("Mauritius", "MU", "MUS", false),
  YT("Mayotte", "YT", "MYT", false),
  MX("Mexico", "MX", "MEX", false),
  FM("Micronesia (Federated States of)", "FM", "FSM", false),
  MD("Moldova (Republic of)", "MD", "MDA", false),
  MC("Monaco", "MC", "MCO", false),
  MN("Mongolia", "MN", "MNG", false),
  ME("Montenegro", "ME", "MNE", false),
  MS("Montserrat", "MS", "MSR", false),
  MA("Morocco", "MA", "MAR", false),
  MZ("Mozambique", "MZ", "MOZ", false),
  MM("Myanmar", "MM", "MMR", false),
  NA("Namibia", "NA", "NAM", false),
  NR("Nauru", "NR", "NRU", false),
  NP("Nepal", "NP", "NPL", false),
  NL("Netherlands", "NL", "NLD", true),
  NC("New Caledonia", "NC", "NCL", false),
  NZ("New Zealand", "NZ", "NZL", false),
  NI("Nicaragua", "NI", "NIC", false),
  NE("Niger", "NE", "NER", false),
  NG("Nigeria", "NG", "NGA", false),
  NU("Niue", "NU", "NIU", false),
  NF("Norfolk Island", "NF", "NFK", false),
  MP("Northern Mariana Islands", "MP", "MNP", false),
  NO("Norway", "NO", "NOR", false),
  OM("Oman", "OM", "OMN", false),
  PK("Pakistan", "PK", "PAK", false),
  PW("Palau", "PW", "PLW", false),
  PS("Palestine, State of", "PS", "PSE", false),
  PA("Panama", "PA", "PAN", false),
  PG("Papua New Guinea", "PG", "PNG", false),
  PY("Paraguay", "PY", "PRY", false),
  PE("Peru", "PE", "PER", false),
  PH("Philippines", "PH", "PHL", false),
  PN("Pitcairn", "PN", "PCN", false),
  PL("Poland", "PL", "POL", true),
  PT("Portugal", "PT", "PRT", true),
  PR("Puerto Rico", "PR", "PRI", false),
  QA("Qatar", "QA", "QAT", false),
  RE("Réunion", "RE", "REU", false),
  RO("Romania", "RO", "ROU", true),
  RU("Russian Federation", "RU", "RUS", false),
  RW("Rwanda", "RW", "RWA", false),
  BL("Saint Barthélemy", "BL", "BLM", false),
  SH("Saint Helena, Ascension and Tristan da Cunha", "SH", "SHN", false),
  KN("Saint Kitts and Nevis", "KN", "KNA", false),
  LC("Saint Lucia", "LC", "LCA", false),
  MF("Saint Martin (French part)", "MF", "MAF", false),
  PM("Saint Pierre and Miquelon", "PM", "SPM", false),
  VC("Saint Vincent and the Grenadines", "VC", "VCT", false),
  WS("Samoa", "WS", "WSM", false),
  SM("San Marino", "SM", "SMR", false),
  ST("Sao Tome and Principe", "ST", "STP", false),
  SA("Saudi Arabia", "SA", "SAU", false),
  SN("Senegal", "SN", "SEN", false),
  RS("Serbia", "RS", "SRB", false),
  SC("Seychelles", "SC", "SYC", false),
  SL("Sierra Leone", "SL", "SLE", false),
  SG("Singapore", "SG", "SGP", false),
  SX("Sint Maarten (Dutch part)", "SX", "SXM", false),
  SK("Slovakia", "SK", "SVK", true),
  SI("Slovenia", "SI", "SVN", true),
  SB("Solomon Islands", "SB", "SLB", false),
  SO("Somalia", "SO", "SOM", false),
  ZA("South Africa", "ZA", "ZAF", false),
  GS("South Georgia and the South Sandwich Islands", "GS", "SGS", false),
  SS("South Sudan", "SS", "SSD", false),
  ES("Spain", "ES", "ESP", true),
  LK("Sri Lanka", "LK", "LKA", false),
  SD("Sudan", "SD", "SDN", false),
  SR("Suriname", "SR", "SUR", false),
  SJ("Svalbard and Jan Mayen", "SJ", "SJM", false),
  SZ("Swaziland", "SZ", "SWZ", false),
  SE("Sweden", "SE", "SWE", true),
  CH("Switzerland", "CH", "CHE", false),
  SY("Syrian Arab Republic", "SY", "SYR", false),
  TW("Taiwan, Province of China[a]", "TW", "TWN", false),
  TJ("Tajikistan", "TJ", "TJK", false),
  TZ("Tanzania, United Republic of", "TZ", "TZA", false),
  TH("Thailand", "TH", "THA", false),
  TL("Timor-Leste", "TL", "TLS", false),
  TG("Togo", "TG", "TGO", false),
  TK("Tokelau", "TK", "TKL", false),
  TO("Tonga", "TO", "TON", false),
  TT("Trinidad and Tobago", "TT", "TTO", false),
  TN("Tunisia", "TN", "TUN", false),
  TR("Turkey", "TR", "TUR", false),
  TM("Turkmenistan", "TM", "TKM", false),
  TC("Turks and Caicos Islands", "TC", "TCA", false),
  TV("Tuvalu", "TV", "TUV", false),
  UG("Uganda", "UG", "UGA", false),
  UA("Ukraine", "UA", "UKR", false),
  AE("United Arab Emirates", "AE", "ARE", false),
  GB("United Kingdom of Great Britain and Northern Ireland", "GB", "GBR", true),
  US("United States of America", "US", "USA", false),
  UM("United States Minor Outlying Islands", "UM", "UMI", false),
  UY("Uruguay", "UY", "URY", false),
  UZ("Uzbekistan", "UZ", "UZB", false),
  VU("Vanuatu", "VU", "VUT", false),
  VE("Venezuela (Bolivarian Republic of)", "VE", "VEN", false),
  VN("Viet Nam", "VN", "VNM", false),
  VG("Virgin Islands (British)", "VG", "VGB", false),
  VI("Virgin Islands (U.S.)", "VI", "VIR", false),
  WF("Wallis and Futuna", "WF", "WLF", false),
  EH("Western Sahara", "EH", "ESH", false),
  YE("Yemen", "YE", "YEM", false),
  ZM("Zambia", "ZM", "ZMB", false),
  ZW("Zimbabwe", "ZW", "ZWE", false);

  private final String name;
  private final String alpha2code;
  private final String alpha3code;
  private final boolean EU;

  private Country(
      final String name, final String alpha2code, final String alpha3code, final boolean EU) {
    this.name = name;
    this.alpha2code = alpha2code;
    this.alpha3code = alpha3code;
    this.EU = EU;
  }

  public String getName() {
    return name;
  }

  public String getAlpha2code() {
    return alpha2code;
  }

  public String getAlpha3code() {
    return alpha3code;
  }

  public boolean isEU() {
    return EU;
  }

  public static final Collection<Country> getEUCountries() {
    return Arrays.stream(values()).filter(country -> country.isEU()).collect(Collectors.toList());
  }
}
