FROM mysql:5.7

# Set environment variables
ENV MYSQL_DATABASE atmosphere
ENV MYSQL_USER app
ENV MYSQL_PASSWORD rfEofrL1BnZuA7PMOyNz5Fq5zD10Wa24
ENV MYSQL_ROOT_PASSWORD rfEofrL1BnZuA7PMOyNz5Fq5zD10Wa24

# Initialize database
#COPY ./db.sql /docker-entrypoint-initdb.d

# Start database
CMD ["mysqld"]